version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: symfony/string
    versions:
    - 5.2.6
  - dependency-name: psr/container
    versions:
    - 1.1.1
  - dependency-name: symfony/filesystem
    versions:
    - 5.2.3
  - dependency-name: slevomat/coding-standard
    versions:
    - 6.4.1
  - dependency-name: composer/xdebug-handler
    versions:
    - 1.4.5
  - dependency-name: object-calisthenics/phpcs-calisthenics-rules
    versions:
    - 3.9.1
  - dependency-name: nette/utils
    versions:
    - 3.2.1
  - dependency-name: composer/semver
    versions:
    - 1.7.2
  - dependency-name: paragonie/random_compat
    versions:
    - 9.99.100
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
  - dependency-name: composer/composer
    versions:
    - 1.10.20
  - dependency-name: symfony/polyfill-php70
    versions:
    - 1.20.0
  - dependency-name: symfony/event-dispatcher-contracts
    versions:
    - 2.2.0
  - dependency-name: symfony/stopwatch
    versions:
    - 5.2.3
  - dependency-name: symfony/finder
    versions:
    - 5.2.3
  - dependency-name: doctrine/annotations
    versions:
    - 1.12.1
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/options-resolver
    versions:
    - 5.2.2
  - dependency-name: symfony/http-client
    versions:
    - 5.2.2
  - dependency-name: symfony/polyfill-mbstring
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.0
  - dependency-name: symfony/http-client-contracts
    versions:
    - 2.3.1
